### ISSUE TITLE
ThaumicBoots does not support thaumcraft's easy mode

### ISSUE THREAD

**Issue by Iamworking12** [Alastors/ThaumicBoots#1]
Pretty straight forward, I loaded the mod with Thaumcraft's easy mode enabled in configs, yet the Thaumic Boots tab still requests for paper and ink. Upon trying to click a research bubble, the game will consume the paper and ink, but will not give anything in return.

**Comment by Alastors** [comment]
Aight, thanks lad, I'll get on it in a few when my time opens back up! <3

**Comment by Alastors** [comment]
@Iamworking12 This is fixed, I am pushing 0.0.0.2 later tonight

**Comment by Alastors** [comment]
fixed
