### ISSUE TITLE
Crash without EMT

### ISSUE THREAD

**Issue by WindFox** [Alastors/ThaumicBoots#24]
Despite what the Modrinth page says about version 1.0.0.0, the mod will not load without EMT.

```
Caught exception from thaumicboots
java.lang.NoClassDefFoundError: emt/util/EMTConfigHandler
```

**Comment by Alastors** [comment]
> Despite what the Modrinth page says about version 1.0.0.0, the mod will not load without EMT.
> 
> 
> 
> ```
> 
> Caught exception from thaumicboots
> 
> java.lang.NoClassDefFoundError: emt/util/EMTConfigHandler
> 
> ```

Weird, should be fixed now, try the latest version, I removed the ConfigHandler references and it should've cleared it up

**Comment by WindFox** [comment]
Finally got around to testing it and it works now.
