### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by lugiaf** [Alastors/ThaumicBoots#26]
(machine translation. Sorry!)

I had a problem with Thaumic Boots 1.0.1.1 obtained from Curse forge.
Here is the crash log

https://pastebin.com/iv6x696B

Crashed after taking damage from an Enemy while wearing Thermal Expansion boots. The server then starts up, but players cannot enter the world.

It seems to be crashing with "ItemElectricCometBoots", so I tried setting "Electro-Magic-Tools=false" in the Config, but this has not solved the problem.

Electro Magic Tools Mod is not installed (because IC2 is not installed).

**Comment by Alastors** [comment]
Aight! I think I know what's causing this

**Comment by shadoxxhd** [comment]
How *does* that class stop existing? Without EMT, it's not getting *registered*, but that shouldn't matter to `instanceof` ...

**Comment by Alastors** [comment]
> How *does* that class stop existing? Without EMT, it's not getting *registered*, but that shouldn't matter to `instanceof` ...

Yeah but it can be referenced elsewhere, if it's caused by falling and things of the like, it's probably in the movement class

**Comment by shadoxxhd** [comment]
it's this line in events/BootsEventHandler line 111:
`if (!(item instanceof ItemElectricCometBoots)) {`
what I'm surprised about is that instanceof shouldn't need ItemElectricCombatBoots to be registered to work. Unless the class is somehow prevented from being loaded in some way I'm not seeing...

**Comment by Alastors** [comment]
Yeah Java is a nut, but basically it comes down to attempting to import libraries that don't exist. I'll have it fixed sometime soon

**Comment by Alastors** [comment]
Aight, I'm about to push a new minor version with a bugfix as well as a couple new boots, hopefully this'll fix it

**Comment by Alastors** [comment]
https://modrinth.com/mod/thaumic_boots/version/1.1.0.0 please re-open this (or open a new ticket) if this doesn't fix your problem! Thank you for using Thaumic Boots!
